Fix a lot
1. deploy_server will download linux-arm32-v5 AMD64 binary into local
2. Fix deploy_router
3. Refactor a lot


Former-commit-id: afb43b634294b9c70b8335f5c3f6ebaa7772f08d

diff --git a/deploy_router b/deploy_router
--- a/deploy_router
+++ b/deploy_router
@@ -1,15 +1,50 @@
 #!/bin/bash
 
-self="$(\curl -sS https://gitlab.com/zw963/deployment_bash/-/raw/v0.8.3/deploy_start.sh)" && eval "$self"
+self="$(\curl -sS https://gitlab.com/zw963/deployment_bash/-/raw/v0.8.7/deploy_start.sh)" && eval "$self"
+# self="$(\cat /home/common/Project/deployment_bash/deploy_start.sh)" && eval "$self"
 
-export target=$1
+export_variable target=$1
+export_variable arch=${router_arch-linux-arm32-v5}
 
-config=./router/opt/etc/v2ray.json
+echo "Set \$router_arch env to e.g. \`linux-arm32-v5' for deploy Xray into ASUS AC5300 router.
+For the correct Arch name, check https://github.com/XTLS/Xray-core/releases assets.
+Current arch using: ${arch}"
 
-if [ ! -e "$config" ];then
-    echo "Please create ${config} or generate it use ./deploy_server before deploy to router."
-    exit
+config_folder=./downloaded_binary/${arch}
+config=${config_folder}/v2ray.json
+
+if [ ! -f "$config" ];then
+    echo "Please create ${config} or generate it use ./deploy_server root@some_ip before deploy to router."
+    exit 1
 fi
+
+assets=(geoip.dat geosite.dat geoip-only-cn-private.dat v2ray xray)
+
+for i in "${assets[@]}"; do
+    if [ ! -f "${config_folder}/$i" ];then
+        echo "${config_folder}/$i is missing, predownload it use ./deploy_server root@some_ip before deploy to router."
+        exit 1
+    fi
+done
+
+echo 'Copy downloaded binary to router ...'
+copy $config_folder downloaded_binary
+
+if cat $config |grep -qs '"protocol": "vless"'; then
+    service_name=xray
+else
+    service_name=v2ray
+fi
+
+if [ "$use_xtls" ]; then
+    export_variable service_name=xray
+else
+    export_variable service_name=${service_name}
+fi
+
+echo "Set \$use_xtls=true if prefer deploy Xray instead of V2ray.
+Current auto-detect: ${service_name}.
+"
 
 function postinstall () {
     set -u
@@ -23,10 +58,9 @@ function postinstall () {
         echo 'visit google failed, something was wrong!'
     fi
 }
-copy "$config" /opt/etc/
+
 copy router/opt/etc/apply_iptables_rule.sh /opt/etc/
 copy router/opt/etc/clean_iptables_rule.sh /opt/etc
-copy router/opt/etc/enable_swap.sh /opt/etc
 copy router/opt/etc/update_geodata.sh /opt/etc
 copy router/opt/etc/restart_dnsmasq.sh /opt/etc
 copy router/opt/etc/toggle_proxy.sh /opt/etc
@@ -34,16 +68,6 @@ copy router/opt/etc/patch_router /opt/etc
 copy router/opt/etc/check_google_use_proxy.sh /opt/etc
 copy router/opt/etc/check_google_use_socks5.sh /opt/etc
 copy router/opt/etc/debug_v2ray.sh /opt/etc
-
-if [ -d downloaded_binary ]; then
-    echo 'Copy downloaded binary to router ...'
-    mkdir -p downloaded_binary
-    scp -r downloaded_binary/arm32 $target:download_binary
-else
-    ssh "$*" "rm -rf downloaded_binary"
-    echo "Please run \`use_tls=true ./deploy_server root@some_ip' first to copy binary into downloaded_binary, then retry."
-    exit 1
-fi
 
 deploy_start
 
@@ -88,32 +112,32 @@ fi
 
 cd downloaded_binary
 
-if ./v2ray -version; then
-    set +e
-    chmod -x /opt/etc/init.d/S22v2ray && sh /opt/etc/init.d/S22v2ray stop
-    set -e
-    cp v2ray v2ctl geosite.dat geoip-only-cn-private.dat /opt/sbin/
-else
-    echo 'Not valid v2ray version is supported by current router, please download correct version.'
+if ! ./$service_name version &>/dev/null; then
+    echo "Invalid $service version/arch supported by current router, please download correct version."
     exit
 fi
 
-cat <<'HEREDOC' > /opt/etc/init.d/S22v2ray
+set +e
+chmod -x /opt/etc/init.d/S22v2ray && sh /opt/etc/init.d/S22v2ray stop
+set -e
+cp $service_name geosite.dat geoip-only-cn-private.dat /opt/sbin/
+cp v2ray.json /opt/etc
+
+
+cat <<HEREDOC > /opt/etc/init.d/S22v2ray
 #!/bin/sh
 
 ENABLED=yes
-PROCS=v2ray
-ARGS="-config /opt/etc/v2ray.json"
+PROCS=$service_name
+ARGS="run -config /opt/etc/v2ray.json"
 PREARGS=""
-DESC=$PROCS
+DESC=\$PROCS
 PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
 
-[ -z "$(which $PROCS)" ] && exit 0
+[ -z "\$(which \$PROCS)" ] && exit 0
 
 . /opt/etc/init.d/rc.func
 HEREDOC
-
-echo 'v2ray was installed.'
 
 # ----------------------------------------------------
 #
@@ -140,22 +164,22 @@ chmod +x apply_iptables_rule.sh \
 #
 # ---------------------------------------------------
 
-# 每隔 3 分钟检测下所有的服务是否运行, 以及 iptables rule 是否失效.
-add_service wan-start 'cru a run-services "*/3 * * * * /jffs/scripts/services-start"'
-add_service wan-start 'cru a run-iptables "*/3 * * * * /opt/etc/apply_iptables_rule.sh"'
-# 每个周日的 5: 25 升级一次 geosites 数据.
-add_service wan-start 'cru a update_geodata "25 5 * * 0 /opt/etc/update_geodata.sh"'
-/jffs/scripts/wan-start
+# # 每隔 3 分钟检测下所有的服务是否运行, 以及 iptables rule 是否失效.
+# add_service wan-start 'cru a run-services "*/3 * * * * /jffs/scripts/services-start"'
+# add_service wan-start 'cru a run-iptables "*/3 * * * * /opt/etc/apply_iptables_rule.sh"'
+# # 每个周日的 5: 25 升级一次 geosites 数据.
+# add_service wan-start 'cru a update_geodata "25 5 * * 0 /opt/etc/update_geodata.sh"'
+# /jffs/scripts/wan-start
 
-# Because newest asus merlin introduce AMTM, please enable swap file there if need it.
-# 打开swap
-# echo 'Enabling swap'
-# /opt/etc/enable_swap.sh
-# add_service post-mount '/opt/etc/enable_swap.sh'
+# # Because newest asus merlin introduce AMTM, please enable swap file there if need it.
+# # 打开swap
+# # echo 'Enabling swap'
+# # /opt/etc/enable_swap.sh
+# # add_service post-mount '/opt/etc/enable_swap.sh'
 
-# 如果 DHCP 重新分配 IP 地址时, 会清除 iptables rule, 此时重新应用 iptables
-add_service dhcpc-event '/opt/etc/apply_iptables_rule.sh'
+# # 如果 DHCP 重新分配 IP 地址时, 会清除 iptables rule, 此时重新应用 iptables
+# add_service dhcpc-event '/opt/etc/apply_iptables_rule.sh'
 
-add_service services-start '[ -f /tmp/patch_router_was_run_at ] || /opt/etc/patch_router'
+# add_service services-start '[ -f /tmp/patch_router_was_run_at ] || /opt/etc/patch_router'
 
 /opt/etc/patch_router && echo "Congratulations, [0m[33mDeploy succssful[0m!"
diff --git a/deploy_server b/deploy_server
--- a/deploy_server
+++ b/deploy_server
@@ -1,31 +1,40 @@
 #!/bin/sh
 
-self="$(\curl -sS https://gitlab.com/zw963/deployment_bash/-/raw/v0.8.6/deploy_start.sh)" && eval "$self"
+self="$(\curl -sS https://gitlab.com/zw963/deployment_bash/-/raw/v0.8.7/deploy_start.sh)" && eval "$self"
 
-export target=$1
-export use_xtls="$use_xtls"
-export old_uuid=$(ssh $target cat /etc/xray/config.json 2>/dev/null |grep '"flow": "xtls-rprx' -B3 |grep '"id":' |cut -d: -f2 |cut -d'"' -f2)
+export_variable target=$1
+export_variable use_xtls="${use_xtls-true}"
+export_variable old_uuid=$(ssh $target cat /etc/xray/config.json 2>/dev/null |grep '"flow": "xtls-rprx' -B3 |grep '"id":' |cut -d: -f2 |cut -d'"' -f2)
+export_variable arch=${router_arch-linux-arm32-v5}
 
-if [ "$use_xtls" ]; then
-    export service_name=xray
-    export another_service_name=v2ray
+echo "Set \$router_arch env to e.g. \`linux-arm32-v5/' if you want deploy to an asuswrt merlin AC5300 router.
+For the correct Arch name, check https://github.com/XTLS/Xray-core/releases assets.
+The default arch will assume server and side router use linux-amd64, and router using  ${arch}."
+
+if [ "$use_xtls" == "true" ]; then
+    export_variable service_name=xray
+    export_variable another_service_name=v2ray
 else
-    export service_name=v2ray
-    export another_service_name=xray
+    export_variable service_name=v2ray
+    export_variable another_service_name=xray
 fi
 
 function postinstall () {
     set -u
-    mkdir -p ./downloaded_binary/amd64
+    mkdir -p ./downloaded_binary/linux-amd64/services ./downloaded_binary/${arch}
     echo
     echo 'Please wait copy generated client config into local machine ...'
-    scp $target:/etc/$service_name/v2ray.json ./downloaded_binary/
-    scp $target:/usr/local/bin/{geoip-only-cn-private.dat,geoip.dat,geosite.dat,v2ray,xray} ./downloaded_binary/amd64/
-    scp $target:/etc/systemd/system/{v2ray.service,v2ray@.service} ./downloaded_binary/amd64/services/
-    cp router/opt/etc/{apply_iptables_rule.sh,clean_iptables_rule.sh,update_geodata.sh} ./downloaded_binary/amd64/
-    cd ./downloaded_binary/amd64/
+    scp  $target:/etc/$service_name/v2ray.json ./downloaded_binary/linux-amd64
+    scp  $target:/usr/local/bin/{geoip-only-cn-private.dat,geoip.dat,geosite.dat,xray,v2ray} ./downloaded_binary/linux-amd64/
+    scp  $target:/etc/systemd/system/{v2ray.service,v2ray@.service} ./downloaded_binary/linux-amd64/services/
+    cp router/opt/etc/{apply_iptables_rule.sh,clean_iptables_rule.sh,update_geodata.sh} ./downloaded_binary/linux-amd64/
+    cd ./downloaded_binary/linux-amd64/
     chmod +x apply_iptables_rule.sh clean_iptables_rule.sh update_geodata.sh xray v2ray
-    echo "Run [0m[33m./deploy_router admin@192.168.50.1[0m to deploy to router."
+
+    cp ./downloaded_binary/linux-amd64/{geoip-only-cn-private.dat,geoip.dat,geosite.dat,v2ray.json} ./downloaded_binary/${arch}/
+    scp  $target:/tmp/v2ray-clients/{xray,v2ray} ./downloaded_binary/${arch}/
+
+    echo "Run [0m[33m./deploy_router admin@router_ip[0m to deploy to router."
     echo "Run [0m[33m./deploy_side_router root@side_router_ip[0m to deploy to side_router."
 }
 
@@ -46,8 +55,8 @@ fi
 
 copy xray_server.json /etc/xray/config.json
 copy v2ray_server.json /etc/v2ray/config.json
-copy downloaded_binary/amd64/services/xray.service /etc/systemd/system/xray.service
-copy downloaded_binary/amd64/services/xray@.service /etc/systemd/system/xray@.service
+copy downloaded_binary/linux-amd64/services/xray.service /etc/systemd/system/xray.service
+copy downloaded_binary/linux-amd64/services/xray@.service /etc/systemd/system/xray@.service
 
 deploy_start
 
@@ -73,30 +82,49 @@ fi
 
 xray_version=$(github_latest_release XTLS/Xray-core)
 v2ray_version=$(github_latest_release v2fly/v2ray-core)
-arch=linux-64
 
 set -e
 
-download_and_extract https://github.com/XTLS/Xray-core/releases/download/${xray_version}/Xray-${arch}.zip Xray-${xray_version}
-cd Xray-${xray_version} && chmod +x xray
+(
+    download_and_extract https://github.com/XTLS/Xray-core/releases/download/${xray_version}/Xray-linux-64.zip Xray-${xray_version}-linux-64
 
-if ! ./xray --version &>/dev/null; then
-    echo 'Invalid xray version, please check if download correct version.'
-    exit
-fi
+    cd Xray-${xray_version}-linux-64 && chmod +x xray
 
-cp xray /usr/local/bin
+    if ! ./xray version &>/dev/null; then
+        echo 'Invalid xray version/arch, please download correct version.'
+        exit
+    fi
 
-download_and_extract https://github.com/v2fly/v2ray-core/releases/download/${v2ray_version}/v2ray-${arch}.zip v2ray-${v2ray_version}
-cd v2ray-${v2ray_version} && chmod +x v2ray
+    cp xray *.dat /usr/local/bin
+)
 
-if ! ./v2ray version &>/dev/null; then
-    echo 'Invalid v2ray version, please check if download correct version.'
-    exit
-fi
+(
+    download_and_extract https://github.com/XTLS/Xray-core/releases/download/${xray_version}/Xray-${arch}.zip Xray-${xray_version}-${arch}
 
-cp v2ray *.dat /usr/local/bin &&
-    cp systemd/system/*.service /etc/systemd/system
+    mkdir -p /tmp/v2ray-clients
+    cd Xray-${xray_version}-${arch} && cp xray *.dat /tmp/v2ray-clients
+)
+
+(
+    download_and_extract https://github.com/v2fly/v2ray-core/releases/download/${v2ray_version}/v2ray-linux-64.zip v2ray-${v2ray_version}-linux-64
+
+    cd v2ray-${v2ray_version}-linux-64 && chmod +x v2ray
+
+    if ! ./v2ray version &>/dev/null; then
+        echo 'Invalid v2ray version/arch, please download correct version.'
+        exit
+    fi
+
+    cp v2ray *.dat /usr/local/bin &&
+        cp systemd/system/*.service /etc/systemd/system
+)
+
+(
+    download_and_extract https://github.com/v2fly/v2ray-core/releases/download/${v2ray_version}/v2ray-${arch}.zip v2ray-${v2ray_version}-${arch}
+
+    mkdir -p /tmp/v2ray-clients
+    cd v2ray-${v2ray_version}-${arch} && cp v2ray *.dat /tmp/v2ray-clients
+)
 
 replace_regex 'RestartPreventExitStatus=23' 'RestartPreventExitStatus=23
 # Added by user
@@ -110,7 +138,7 @@ replace_regex '/usr/local/etc/v2ray/config.json' '/etc/v2ray/config.json' /etc/s
 replace_regex '/usr/local/etc/v2ray/%i.json' '/etc/v2ray/%i.json' /etc/systemd/system/v2ray@.service
 
 mkdir -p /var/log/xray /var/log/v2ray
-chown nobody:nobody /var/log/xray /var/log/v2ray
+# chown nobody:nobody /var/log/xray /var/log/v2ray
 
 if [ "$old_uuid" != NEWUUID ]; then
     uuid=$old_uuid
@@ -124,12 +152,9 @@ replace_string 'NEWUUID' "${uuid}" /etc/v2ray/config.json
 
 # replace_string 'QUIC_KEY' "${quic_key}" /etc/xray/config.json
 
-if [ "$new_ss_pwd" != "0" ]; then
-    ss_password=$(openssl rand -base64 32)
-
-    replace_string 'SSPASS' "${ss_password}" /etc/xray/config.json
-    replace_string 'SSPASS' "${ss_password}" /etc/v2ray/config.json
-fi
+ss_password=$(openssl rand -base64 32)
+replace_string 'SSPASS' "${ss_password}" /etc/xray/config.json
+replace_string 'SSPASS' "${ss_password}" /etc/v2ray/config.json
 
 config_sysctl_for_proxy
 
@@ -366,8 +391,8 @@ cat <<HEREDOC > /etc/$service_name/v2ray.json
                 ]
             },
             "streamSettings": {
-               "network": "tcp",
-               "security": "tls", // 需要使用 XTLS
+                "network": "tcp",
+                "security": "tls", // 需要使用 XTLS
                 "tlsSettings": {
                     "serverName": "$domain_name" // 换成你的域名
                 },
diff --git a/deploy_side_router b/deploy_side_router
--- a/deploy_side_router
+++ b/deploy_side_router
@@ -1,15 +1,36 @@
 #!/bin/bash
 
-self="$(\curl -sS https://gitlab.com/zw963/deployment_bash/-/raw/v0.8.3/deploy_start.sh)" && eval "$self"
+self="$(\curl -sS https://gitlab.com/zw963/deployment_bash/-/raw/v0.8.7/deploy_start.sh)" && eval "$self"
 
 export target=$1
+export arch=${router_arch-linux-amd64}
 
-config=./router/opt/etc/v2ray.json
+echo "Set \$router_arch env to e.g. \`linux-arm32-v5' for deploy Xray into ASUS AC5300 router.
+For the correct Arch name, check https://github.com/XTLS/Xray-core/releases assets.
+Current arch using: ${arch}"
 
-if [ ! -e "$config" ]; then
+config=./downloaded_binary/v2ray.json
+
+if [ ! -f "$config" ]; then
     echo "Please create ${config} or generate it use ./deploy_server before deploy to side router."
     exit
 fi
+
+if cat $config |grep -qs '"protocol": "vless"'; then
+    service_name=xray
+else
+    service_name=v2ray
+fi
+
+if [ "$use_xtls" ]; then
+    export service_name=xray
+else
+    export service_name=${service_name}
+fi
+
+echo "Set \$use_xtls=true if deploy Xray instead of V2ray.
+Current auto-detect: ${service_name}.
+"
 
 function postinstall () {
     set -u
@@ -36,12 +57,10 @@ copy router/opt/etc/check_google_use_proxy.sh /opt/etc
 copy router/opt/etc/check_google_use_socks5.sh /opt/etc
 copy router/opt/etc/debug_v2ray.sh /opt/etc
 
-if [ -d downloaded_binary ]; then
+if [ -d downloaded_binary/${arch} ]; then
     echo 'Copy downloaded binary to router ...'
-    mkdir -p downloaded_binary
-    scp -r downloaded_binary/amd64 $target:download_binary
+    copy downloaded_binary/${arch} downloaded_binary
 else
-    ssh "$*" "rm -rf downloaded_binary"
     echo "Please run \`use_tls=true ./deploy_server root@some_ip' first to copy binary into downloaded_binary, then retry."
     exit 1
 fi
@@ -85,25 +104,25 @@ set -eu
 
 cd downloaded_binary
 
-if ./xray -version; then
-    set +e; systemctl stop v2ray; set -e
-    cp xray geosite.dat geoip-only-cn-private.dat /opt/sbin/
-    cp systemd/system/*.service /etc/systemd/system
-    replace_regex1 'RestartPreventExitStatus=23' 'RestartPreventExitStatus=23
+if ! ./$service_name version &>/dev/null; then
+    echo "Invalid $service version/arch supported by current side router, please download correct version."
+    exit
+fi
+
+set +e; systemctl stop v2ray; set -e
+cp $service geosite.dat geoip-only-cn-private.dat /opt/sbin/
+cp systemd/system/*.service /etc/systemd/system
+replace_regex1 'RestartPreventExitStatus=23' 'RestartPreventExitStatus=23
 # Added by user
 LimitNPROC=500
 LimitNOFILE=1000000' /etc/systemd/system/v2ray.service
-    replace_regex1 'RestartPreventExitStatus=23' 'RestartPreventExitStatus=23
+replace_regex1 'RestartPreventExitStatus=23' 'RestartPreventExitStatus=23
 # Added by user
 LimitNPROC=500
 LimitNOFILE=1000000' /etc/systemd/system/v2ray@.service
-    replace_string1 '/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json' '/opt/sbin/xray run -config /opt/etc/v2ray.json' /etc/systemd/system/v2ray.service
-    replace_string1 '/usr/local/bin/v2ray -config /usr/local/etc/v2ray/%i.json' '/opt/sbin/xray run -config /opt/etc/%i.json' /etc/systemd/system/v2ray@.service
-    systemctl daemon-reload
-else
-    echo 'Not valid xray version is supported by current router, please download correct version.'
-    exit
-fi
+replace_string1 '/usr/local/bin/v2ray -config /usr/local/etc/v2ray/config.json' '/opt/sbin/xray run -config /opt/etc/v2ray.json' /etc/systemd/system/v2ray.service
+replace_string1 '/usr/local/bin/v2ray -config /usr/local/etc/v2ray/%i.json' '/opt/sbin/xray run -config /opt/etc/%i.json' /etc/systemd/system/v2ray@.service
+systemctl daemon-reload
 
 echo 'xray is installed'
 
@@ -123,12 +142,8 @@ chmod +x apply_iptables_rule.sh \
       check_google_use_socks5.sh \
       debug_v2ray.sh
 
-# 旁路由直接在 53 端口监听
+# 默认配置文件适用于路由器配合 dnsmasq 一起使用，使用旁路由时，直接在 53 端口监听即可。
 replace_string '65053' '53' /opt/etc/v2ray.json
-
-# 下面的 iptables 在旁路由模式下，无需设置。
-replace_string 'iptables -t mangle -A V2RAY_UDP -d 192.168.0.0/16 -p udp ! --dport 53 -j RETURN' 'iptables -t mangle -A V2RAY_UDP -d 192.168.0.0/16 -p udp -j RETURN' /opt/etc/apply_iptables_rule.sh
-replace_regex 'iptables -t mangle -A V2RAY_UDP -p udp -j TPROXY --tproxy-mark 1 --on-port \$local_v2ray_port' '' /opt/etc/apply_iptables_rule.sh
 
 /opt/etc/clean_iptables_rule.sh && chmod -x /opt/etc/apply_iptables_rule.sh
 chmod +x /opt/etc/apply_iptables_rule.sh && /opt/etc/apply_iptables_rule.sh
